[package]
name = "roniai"
authors = ["Frederik Enste <frederik@fenste.de>"]
version = "0.1.0"
edition = "2024"
rust-version = "1.95.0"
publish = false

[dependencies]
anyhow = "1.0.102"
encoding_rs = "0.8.35"
#llama-cpp-2 = { version = "0.1.146", features = ["cuda"] }
qwen3-tts = {git = "https://github.com/TrevorS/qwen3-tts-rs.git", rev = "711ceee07cad92673f86de8997bdf54c30caa49f", features = ["cuda"]}
serde_json = "1.0.149"
