name: roniai
services:
  frontend:
    build:
      context: ../..
      dockerfile: deploy/docker/frontend.dockerfile
      tags:
        - roniai/frontend:local
      args:
        - PUBLIC_WEBSOCKET_URL=wss://roniai-backend.mrsroni.de/ws/mrsroni
    restart: unless-stopped
    ports:
      - "80:80"